### ISSUE TITLE
Update RAPIDS repos for RMM pool and detail API improvements

### ISSUE THREAD

**Issue by harrism** [rapidsai/build-planning#10]
rapidsai/rmm#1417 and a followon PR makes a number of improvements and changes to help consumers of RMM avoid accessing RMM's `detail` namespace.

* initial pool size in `pool_memory_resource` is required to be provided (no longer optional)
* rmm::detail::available_device_memory() (moving to `rmm::available_device_memory())
* Move alignment utility functions out of `detail` namespace.
* Add utility to calculate an aligned percentage of free device memory in bytes. This way, existing instantiations of `pool_memory_resource<Upstream>(upstream)` can be replaced by `pool_memory_resource<Upstream>(upstream, rmm::percent_of_free_device_memory(50)`, which matches previous behavior.

All RAPIDS repos that use any of the above will need to be updated. rapidsai/rmm#1417 only adds functionality. A follow on PR(s) will deprecate / remove functionality after RAPIDS repos are updated. Based on a search, the following repo issues cover the required changes.

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/cudf/issues/14658
- [ ] rapidsai/raft#2087
- [ ] https://github.com/rapidsai/cugraph/issues/4066
- [ ] https://github.com/rapidsai/cuspatial/issues/1318
```

**Comment by harrism** [comment]
Finished.
