### ISSUE TITLE
Add validation on wheel file characteristics in CI

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/build-planning#110]
## Description

As we start to publish more RAPIDS wheels directly to https://pypi.org/, it'll be important to validate the following characteristics:

* README is well-formatted and metadata is correct
  - *(because the README is rendered into the project homepage, e.g. https://pypi.org/project/numpy/)*
* individual file sizes are within PyPI's limits
  - *(100 MiB by default, larger for projects where we've been given exceptions, like https://github.com/pypi/support/issues/4893)*

These and any other non-functional characteristics of wheels that can be validated easily, quickly, and programmatically should be validated in CI.

## Benefits of this work

* improves release confidence ... reduces the risk of "oops these wheels are too big for PyPI" surprises near the end of a release
* reduces the effort required to identify which changes led to increases in wheel sizes
  - *similar to how setting a test coverage threshold works*
  - *ref: https://github.com/rapidsai/build-planning/issues/33#issuecomment-2032219914*

## Acceptance Criteria

* CI for RAPIDS libraries fails on pull requests when wheel builds produce wheels that:
  - do not pass `twine check --strict`
  - are too large (compressed)

## Approach

Such checks should run in wheel-building CI jobs, on PRs... they don't require GPUs, and should run so quickly that it isn't worth the spin-up time and cost of a dedicated `wheel-validation` CI job.

This could be accomplished with something like the following in wheel-build scripts, after the wheel file is finalized (e.g. has gone through `auditwheel repair`).

```shell
# check README formatting
twine check --strict dist/*

# assert size, and print a summary of contents
pydistcheck \
  --inspect \
  --select 'distro-too-large-compressed' \
  --max-allowed-size-compressed '100M' \
  ./delete-me/*
```

<details><summary>example of this using 24.12 libcudf-cu12 nightlies (click me)</summary>

On an x86_64 linux system:

```shell
mkdir -p ./delete-me
pip download \
    --extra-index-url https://pypi.anaconda.org/rapidsai-wheels-nightly/simple/ \
    --no-deps \
    -d ./delete-me \
    'libcudf-cu12==24.12.*,>=0.0.0a0'
```

Checking the formatting.

```shell
twine check --strict ./delete-me/*
```

```text
Checking ./delete-me/libcudf_cu12-24.12.0a223-py3-none-manylinux_2_28_x86_64.whl: PASSED
```

And checking the size (using `5M` just to show how this would fail in CI if the wheels got too big):

```shell
pydistcheck \
  --inspect \
  --select 'distro-too-large-compressed' \
  --max-allowed-size-compressed '5M' \
  ./delete-me/*
```

```text
==================== running pydistcheck ====================

checking './delete-me/libcudf_cu12-24.12.0a223-py3-none-manylinux_2_28_x86_64.whl'
----- package inspection summary -----
file size
  * compressed size: 0.4G
  * uncompressed size: 0.7G
  * compression space saving: 35.2%
contents
  * directories: 163
  * files: 1974 (2 compiled)
size by extension
  * .so - 0.6G (97.0%)
  * .h - 6.7M (1.0%)
  * no-extension - 5.3M (0.8%)
  * .cuh - 3.8M (0.6%)
  * .hpp - 2.2M (0.3%)
  * .a - 1.2M (0.2%)
  * .inl - 0.8M (0.1%)
  * .cmake - 0.1M (0.0%)
  * .md - 8.3K (0.0%)
  * .py - 3.6K (0.0%)
  * .pc - 0.2K (0.0%)
  * .txt - 34.0B (0.0%)
largest files
  * (0.6G) libcudf/lib64/libcudf.so
  * (3.8M) libcudf/bin/flatc
  * (1.1M) libcudf/lib64/libflatbuffers.a
  * (0.5M) libcudf/include/libcudf/rapids/libcudacxx/cuda/std/__atomic/functions/cuda_ptx_generated.h
  * (0.2M) libcudf_cu12-24.12.0a223.dist-info/RECORD
------------ check results -----------
1. [distro-too-large-compressed] Compressed size 0.4G is larger than the allowed size (5.0M).
errors found while checking: 1

==================== done running pydistcheck ===============
```

```shell
echo $?
# 1
```

</details>

This should be rolled out to all RAPIDS projects producing wheels, starting with those targeting publishing to https://pypi.org/.

### Disclaimer

`pydistcheck` is something I (@jameslamb) created and am currently the sole contributor on, so I'm biased about it being the best tool for this purpose.

The narrow goal here, "assert files are not too big", could be accomplished other ways... like unzipping the wheel and using some mix of `stat` / `du` / `find -size`, or with a Python script.

I think the summaries `pydistcheck` generates (see "Approach" section) and all the others things we could ask it to check in the future ([docs link](https://pydistcheck.readthedocs.io/en/latest/check-reference.html)) make it preferable to those approaches, but I shouldn't be the one to decide that.

## Task Lists

```[tasklist]
### Updates
- [x] install validation tools in CI images (https://github.com/rapidsai/ci-imgs/pull/205)
- [x] cucim (https://github.com/rapidsai/cucim/pull/797)
- [x] cudf (https://github.com/rapidsai/cudf/pull/17284)
- [x] cugraph (https://github.com/rapidsai/cugraph/pull/4754)
- [x] cugraph-gnn (https://github.com/rapidsai/cugraph-gnn/pull/67)
- [x] cuml (https://github.com/rapidsai/cuml/pull/6136)
- [x] cuopt (https://github.com/rapidsai/cuopt/pull/2085)
- [x] cuspatial (https://github.com/rapidsai/cuspatial/pull/1482)
- [x] cuvs (https://github.com/rapidsai/cuvs/pull/464, https://github.com/rapidsai/cuvs/pull/469)
- [x] cuxfilter (https://github.com/rapidsai/cuxfilter/pull/643)
- [x] dask-cuda (https://github.com/rapidsai/dask-cuda/pull/1404)
- [x] jupyterlab-nvdashboard (https://github.com/rapidsai/jupyterlab-nvdashboard/pull/208)
- [x] kvikio (https://github.com/rapidsai/kvikio/pull/548)
- [x] nx-cugraph (https://github.com/rapidsai/nx-cugraph/pull/19)
- [x] pynvjitlink (skipping: see https://github.com/rapidsai/pynvjitlink/pull/114#discussion_r1842820763)
- [x] raft (https://github.com/rapidsai/raft/pull/2490)
- [x] rmm (https://github.com/rapidsai/rmm/pull/1726)
- [x] ucx-py (https://github.com/rapidsai/ucx-py/pull/1092)
- [x] ucxx (https://github.com/rapidsai/ucxx/pull/319)
```

**Comment by bdice** [comment]
I took a brief look at `pydistcheck` and would support adopting it. It seems like a great tool for this job. It's also good to lean into your expertise in this area. 👍

**Comment by vyasr** [comment]
Yup I'm happy with trying out pydistcheck. Maybe we should do a group review of it in a future build-infra team meeting to make sure we're all aligned. Adding a size check to CI is definitely critical so that we know when someone tries to add a feature that suddenly bloats binary size.

**Comment by jameslamb** [comment]
This is complete. Thanks everyone!
