### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#120]
## Overview

Python 3.13 was released in October 2024. This issue tracks the work to add support for Python 3.13 to RAPIDS.

Prior work:
- #40 added support for Python 3.12 (RAPIDS 24.10)
- #3 added support for Python 3.11 (RAPIDS 24.04)

We now have excellent automation for this process thanks to @jameslamb. We can use `rapids-reviser` with this example script, which we should update to "add 3.13" instead of 3.12: https://github.com/rapidsai/rapids-reviser/tree/main/examples/add-python-3.12

**Note: We would like to complete our work on C++ wheels (#33) before adding Python 3.13 support, to keep CI build time down.**

### When should we drop Python 3.10?
Typically RAPIDS has kept the matrix of supported Python minor versions to ~3 versions at a time. However, I don't think we should drop Python 3.10 at the same time (explained below).

[SPEC 0](https://scientific-python.org/specs/spec-0000/) recommended dropping support for Python 3.10 in 2024Q4. Meanwhile, [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommended dropping support for Python 3.10 as of Apr 04, 2025. SPEC 0 is more aggressive, and we have not yet passed the deadline for NEP 29. Because of this, we probably want to leave Python 3.10 for now. Previously we have had concerns about build / test times for a larger Python matrix. However, there have been other advances that help us: through the introduction of C++ wheels (#33), we have moved most of our build time into the C++ wheels, and the Python wheels are comparatively very fast. Eventually we still hope to use the Limited API to reduce the number of Python wheels we must build.

## Tasks

Each section should be fully completed before moving to the next section.

### CI images
- [x] Add Python 3.13 CI images (`ci-conda`, `ci-wheel`, `citestwheel`) https://github.com/rapidsai/ci-imgs/pull/207

### CI workflows
Branch Strategy:
- [x] Create a branch on `shared-workflows` called `python-3.13`
- [x] Add Python 3.13 to the build matrix on the `python-3.13` branch
- [x] Add Python 3.13 to the test matrix on the `python-3.13` branch
  - When adjusting the test matrix, be aware of _total GPU resource consumption_. Build jobs are CPU only but test jobs require GPUs. We want to keep our GPU consumption the same (don't increase the test matrix size), by making it a bit sparser in its coverage. We have some [rough guidelines for how to decide on the matrix entries to include](https://github.com/rapidsai/build-planning/issues/5#issuecomment-1973775147).

The above tasks are handled by: https://github.com/rapidsai/shared-workflows/pull/268

### RAPIDS repositories

This list is intentionally in RAPIDS dependency order... they'll need to be completed in roughly that order.

Consult #40 for example PRs for any necessary work that _isn't_ handled by `rapids-reviser`.

### Updates for libraries
- [ ] pin Python version to 3.12 in `devcontainers` until all repos are migrated
- [x] update `pypi-wheel-scripts` and manually build/publish `cubinlinker` and `ptxcompiler` wheels (https://github.com/rapidsai/pypi-wheel-scripts/pull/28)
- [x] rapids-cmake https://github.com/rapidsai/rapids-cmake/pull/834
- [x] rmm https://github.com/rapidsai/rmm/pull/1851
- [x] kvikio https://github.com/rapidsai/kvikio/pull/708
- [x] pynvjitlink
- [x] dask-cuda https://github.com/rapidsai/dask-cuda/pull/1475
- [x] cudf https://github.com/rapidsai/cudf/pull/18648
- [x] After `cudf` is merged
  - [x] update `dask-cuda` test workflows to `python-3.13` https://github.com/rapidsai/dask-cuda/pull/1480
  - [x] update `ucxx` test workflows to `python-3.13` https://github.com/rapidsai/ucxx/pull/409
  - [x] update `ucx-py` test workflows to `python-3.13` https://github.com/rapidsai/ucx-py/pull/1131
- [x] ucx-py https://github.com/rapidsai/ucx-py/pull/1129
- [x] ucxx https://github.com/rapidsai/ucxx/pull/406
- [x] raft https://github.com/rapidsai/raft/pull/2649
- [x] cugraph https://github.com/rapidsai/cugraph/pull/5057
- [x] cugraph-docs https://github.com/rapidsai/cugraph-docs/pull/113
- [x] cugraph-gnn https://github.com/rapidsai/cugraph-gnn/pull/197
  - [ ] ~get a `dgl` build for Python 3.13 (currently blocking)~ (dgl being dropped for 25.08)
  - [x] get the `dgl` tests removed or separated so we can run the rest on Python 3.13
    - [x] https://github.com/rapidsai/cugraph-gnn/pull/201
- [x] nx-cugraph https://github.com/rapidsai/nx-cugraph/pull/132
- [x] after all cugraph variants are in:
  - [x] update remaining `cugraph` workflows to `python-3.13`
  - [x] update remaining `cugraph-gnn` workflows to `python-3.13`
- [x] cuml https://github.com/rapidsai/cuml/pull/6616
- [x] cuvs https://github.com/rapidsai/cuvs/pull/874
- [ ] ~cuspatial~
- [x] cuxfilter https://github.com/rapidsai/cuxfilter/pull/682
- [x] cucim https://github.com/rapidsai/cucim/pull/873
- [ ] private repos
- [x] integration https://github.com/rapidsai/integration/pull/758
- [ ] cuopt https://github.com/rapidsai/cuopt/pull/2464
- [x] cumlprims https://github.com/rapidsai/cumlprims_mg/pull/241
- [x] rapidsmpf https://github.com/rapidsai/rapidsmpf/pull/262

For each repo,
1. Update `.github/workflows/*.yaml` to point to the `python-3.13` branch of `shared-workflows`
2. Update `dependencies.yaml` to add support for Python 3.13.
3. Review any `pyproject.toml` files for necessary changes (classifiers, etc.)
4. Update docs (README, etc) that reference a single Python version to point to the latest (3.13).
5. Once CI passes, merge the PR.

Once all repos are migrated to the `python-3.13` branch, the migration is complete. We merge `python-3.13` into the development branch on `shared-workflows` and then open follow-up PRs to each repo to reset the branches to that development branch. This "reset" is simple and should be automated with rapids-reviser.

### Post-migration
- [x] Update the `ci-imgs` repo's `latest` configuration to use Python 3.13. (rapidsai/ci-imgs#270)
- [x] Update the `docker` repo's build and test matrices, and references in docs (rapidsai/docker#755)
- [x] Update the build matrix in `pypi-wheel-scripts` so that Python 3.13 wheels are uploaded
- [ ] ~Update `rapidsai/dask-build-environment`~ defunct
- [x] update release selector in `docs` (rapidsai/docs#603)
- [x] update all the repos to point at `branch-25.06` on `shared-workflows` again
- [x] move `devcontainers` Python version pin to Python 3.13 (rapidsai/devcontainers#512)
- [x] (after updating all the repos) delete the `python-3.13` branch in `shared-workflows`
- [x] merge any remaining `rapids-reviser` changes

Notes:

The `:latest` image from `ci-imgs` is frequently used by CI jobs for building docs and testing notebooks. Be aware that issues may arise in those jobs.

**Comment by jameslamb** [comment]
Thanks for opening this! Adding one more useful link... the status of the Python 3.13 migration on conda-forge: https://conda-forge.org/status/migration/?name=python313

It'll be difficult to get too far down the RAPIDS dependency graph until that's further along. `numba` doesn't yet have Python 3.13 conda-forge packages (https://github.com/conda-forge/numba-feedstock/pull/149), for example.

**Comment by bdice** [comment]
I updated our CI images and opened a few PRs to start the migration. It seems like there are a few subtasks we will need:
- Allow numba 0.61 at runtime (bump our upper bounds across RAPIDS and work out any incompatibilities)
- Get Python 3.13 wheel builds for nvcomp

Regardless, we can merge changes to pynvjitlink ahead of mainstream RAPIDS libraries, because it is independent of the RAPIDS shared-workflows CI job matrix.

**Comment by bdice** [comment]
Currently we are blocked by nvcomp wheels not supporting Python 3.13. There will be a future release of nvcomp with Python 3.13 support but we would like to support Python 3.13 sooner in RAPIDS.

One solution to this is to make our libkvikio C++ wheels vendor libnvcomp.so, as we did before we started using nvcomp wheels. We discussed this offline with the nvcomp team and it should solve our needs. @jakirkham, would you have interest or bandwidth in working on that? I think it's a matter of changing some CMake options like `USE_NVCOMP_RUNTIME_WHEEL` so that we fetch the nvcomp tarball and vendor it into the libkvikio C++ wheel, rather than relying on the nvcomp wheel at runtime.

After making that change, we would also need to make the libcudf C++ wheel and kvikio Python wheel search for the nvcomp library being shipped in the libkvikio C++ wheel. This is probably either an RPATH change or a "library load" function call, as we have done for other RAPIDS libraries that depend on other RAPIDS C++ wheels or CUDA wheels.

**Comment by jakirkham** [comment]
I'm sorry Bradley. I don't have bandwidth to do this. Would suggest asking at the build-infra meeting

**Comment by mmccarty** [comment]
@jakirkham - Let's chat offline. We need to find a way forward.

**Comment by gforsyth** [comment]
This will probably also necessitate requesting a PyPI size exception for the `libkvikio` wheel, since `libnvcomp.so` is ~100 MB

**Comment by bdice** [comment]
@gforsyth I think it's smaller than that, perhaps when compressed. I see [nvcomp wheels are ~46 MB](https://pypi.org/project/nvidia-nvcomp-cu12/#files) and [conda packages are ~33 MB or less](https://anaconda.org/conda-forge/nvcomp/files). The existing libkvikio size is quite small (< 1 MB) so a size exception probably won't be needed for "libkvikio + vendored nvcomp".

**Comment by gforsyth** [comment]
Ok, I can take a crack at getting this done

**Comment by gforsyth** [comment]
PR ready for review to re-vendor `nvcomp`, to be followed, in the future, by the re-de-vendoring.
https://github.com/rapidsai/kvikio/pull/702

**Comment by gforsyth** [comment]
`cudf` is currently blocked by the upper pin on `numpy`:

```
🐚 mamba create -n numpy python=3.13 'numpy>=1.23,<2.1'

Looking for: ['python=3.13', "numpy[version='>=1.23,<2.1']"]

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following packages are incompatible
├─ numpy >=1.23,<2.1  is installable with the potential options
│  ├─ numpy [1.23.0|1.23.1|...|2.0.2] would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ numpy [1.23.0|1.23.1|...|1.24.1] would require
│  │  └─ python_abi 3.8 *_pypy38_pp73, which requires
│  │     └─ python 3.8.* *_73_pypy, which can be installed;
│  ├─ numpy [1.23.0|1.23.1|...|1.24.4] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ numpy [1.23.0|1.23.1|...|2.0.2] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ numpy [1.23.0|1.23.1|...|1.26.4] would require
│  │  ├─ pypy3.9 [>=7.3.13 |>=7.3.15 ], which requires
│  │  │  └─ python 3.9.* *_73_pypy, which can be installed;
│  │  └─ python_abi 3.9 *_pypy39_pp73, which requires
│  │     └─ python 3.9.* *_73_pypy, which can be installed;
│  ├─ numpy [1.23.4|1.23.5|...|2.0.2] would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ numpy [1.24.2|1.24.3|1.24.4] would require
│  │  └─ pypy3.8 >=7.3.11  with the potential options
│  │     ├─ pypy3.8 7.3.11 would require
│  │     │  └─ python 3.8.* *_73_pypy, which can be installed;
│  │     └─ pypy3.8 7.3.11 would require
│  │        └─ python 3.8.* *_7.3_pypy, which can be installed;
│  ├─ numpy [1.24.2|1.24.3|...|1.26.0] would require
│  │  └─ pypy3.9 [>=7.3.11 |>=7.3.12 ] with the potential options
│  │     ├─ pypy3.9 [7.3.11|7.3.12|7.3.13|7.3.15|7.3.16], which can be installed (as previously explained);
│  │     └─ pypy3.9 7.3.12 would require
│  │        └─ python 3.9.* *_7.3_pypy, which can be installed;
│  └─ numpy [1.26.0|1.26.2|...|2.0.2] would require
│     └─ python_abi 3.12.* *_cp312, which requires
│        └─ python 3.12.* *_cpython, which can be installed;
└─ python 3.13**  is not installable because it conflicts with any installable versions previously reported.
```

**Comment by gforsyth** [comment]
After fixing the `numpy` upper pins, the Cuda 11 jobs ran into a missing `cubinlinker` dependency for Python 3.13 builds.

@raydouglass was kind enough to build and publish the py313 version to `rapidsai` and `rapidsai-nightly`

**Comment by bdice** [comment]
I think we can begin (or update the status of) the items under "Post-migration" now.

**Comment by bdice** [comment]
@gforsyth I think this can be closed now. If there is anything else missing, please feel free to re-open.

**Comment by bdice** [comment]
Apologies. I was probably too quick on closing this. I looked at the PR description again and there were some gray "draft" icons that I misread as purple "merged" icons. I reopened for now.

**Comment by gforsyth** [comment]
I'm inclined to close this.  The `cuopt` Python 3.13 PR won't be viable until after the 25.06 release and I don't think that by itself should keep this open, but I'll ask in our sync today.

**Comment by gforsyth** [comment]
Closing as completed -- `cuOpt` is a special case until their release cadence matches ours.
