### ISSUE TITLE
Automate C++ include grouping and ordering using .clang-format

### ISSUE THREAD

**Issue by harrism** [rapidsai/build-planning#20]
We want to add rules to RAPIDS repos clang-format files to automate the C++ include grouping and ordering to ensure consistency and make it easier to write scripts that insert includes into C++ files. Such scripts would not have to worry about placing the includes in the right place because clang-format will fix up any ordering or grouping problems after running the script. 

Full discussion in the [cuDF PR](https://github.com/rapidsai/cudf/pull/14993#pullrequestreview-1871222493).

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/rmm/issues/1477
- [ ] https://github.com/rapidsai/cudf/issues/15103
- [ ] https://github.com/rapidsai/raft/issues/2193
- [ ] https://github.com/rapidsai/cugraph/issues/4185
- [ ] https://github.com/rapidsai/cuml/issues/5779
- [ ] https://github.com/rapidsai/cuspatial/issues/1345
- [ ] Others?
```

**Comment by harrism** [comment]
I don't want to do more work than necessary. If there are other RAPIDS repos that use rmm::device_memory_resource* then I can do the work, otherwise maybe we can delegate. :)

**Comment by bdice** [comment]
@harrism I'll close this for now, since it seems like all the repos are completed. If you find that more work is needed, please feel free to reopen.
