### ISSUE TITLE
Drop CentOS 7 support in RAPIDS 24.06

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#23]
We plan to drop CentOS 7 (which uses glibc 2.17) in RAPIDS 24.06. https://docs.rapids.ai/notices/rsn0037/

At this time, the new minimum glibc supported by RAPIDS will become 2.28 (used by Rocky 8), because that is the oldest glibc of any operating system we currently support.

This issue documents some of the work items needed to complete the drop in platform support.

### Early 24.06
- [x] Drop test configurations with CentOS 7 (glibc 2.17) and Ubuntu 18.04 (glibc 2.27) from https://github.com/rapidsai/shared-workflows. (We have [already dropped Ubuntu 18.04 support](https://docs.rapids.ai/notices/rsn0024/).)
  - [x] https://github.com/rapidsai/shared-workflows/pull/192
  - [x] https://github.com/rapidsai/shared-workflows/pull/205
  - [x] Testing PR: https://github.com/rapidsai/cudf/pull/15323
  - [x] Remove the shared-workflows [`NEW_MANYLINUX_MATRIX`](https://github.com/rapidsai/shared-workflows/blob/32fa139e681ffbd13487b8ec045aa5643a55fb6d/.github/workflows/wheels-build.yaml#L102). After dropping CentOS 7, RAPIDS will not build `manylinux_2_17` tags. RAPIDS will only produce wheels that support `manylinux_2_28` tags but nothing older.
  - [x] Remove `build-2_28-wheels` option: https://github.com/rapidsai/shared-workflows/pull/195
- [x] Unpin/update GitHub Actions that were pinned to older versions because of updates to GitHub Actions using Node 20 (which does not support CentOS 7)
  - [x] https://github.com/rapidsai/shared-workflows/pull/178
  - [x] Check on `shared-workflows` PRs from `renovate`, including (but not limited to):
    - [x] https://github.com/rapidsai/shared-workflows/pull/134#issuecomment-1747594318
    - [x] https://github.com/rapidsai/shared-workflows/pull/135#issuecomment-1747593720
  - [x] https://github.com/rapidsai/cudf-pandas-integration/pull/109
- [x] Spark-RAPIDS:
  - [x] https://github.com/NVIDIA/spark-rapids/issues/10496
  - [x] https://github.com/NVIDIA/spark-rapids-jni/issues/1991
  - [x] https://github.com/NVIDIA/spark-rapids/pull/10805
  - [x] https://github.com/rapidsai/cudf/pull/15608

### Before 24.06 release
- [x] Update various release scripts (especially wheel related ones which key on the manylinux version): [tracking issue](https://github.com/rapidsai/ops/issues/3112)
   - PRs [listed here](https://github.com/rapidsai/ops/issues/3112#issuecomment-2111104660).
- [x] Update `shared-actions` to use actions with Node 20 (to avoid deprecation warnings)
  - [x] https://github.com/rapidsai/shared-actions/pull/9
- [x] Drop `centos7` and `ubuntu18.04` from the https://github.com/rapidsai/ci-imgs matrix - https://github.com/rapidsai/ci-imgs/pull/139
  - Not required for release. Wait until 24.04 has shipped (and simmered for a bit, in case hotfixes are needed).
- [x] Drop `centos7` from miniforge-cuda matrix: https://github.com/rapidsai/miniforge-cuda/pull/66

### After 24.06 release
- [x] Update [installation guide](https://github.com/rapidsai/docs/blob/1588d1b12c57392038d5c9cebad8d9aac2f9221a/install/install.md?plain=1#L128) - https://github.com/rapidsai/docs/pull/513
- [x] Update [rapids.ai homepage](https://github.com/rapidsai/rapids.ai/blob/775a3183511f9aabf43d0d4ed920efd3ffe8bece/layouts/index.html#L182) - https://github.com/rapidsai/rapids.ai/pull/379

Feel free to edit this checklist with more items.

References:
- https://endoflife.date/centos
- https://endoflife.date/ubuntu

**Comment by jakirkham** [comment]
We talked with Ray and he resolved the remaining issues needed before 24.06 ships

The remaining items are to be done after 24.06 ships

So nothing to do until 24.06 ships

**Comment by bdice** [comment]
This is now complete!
