### ISSUE TITLE
Deploy new copyright update script to all RAPIDS repos

### ISSUE THREAD

**Issue by KyleFromNVIDIA** [rapidsai/build-planning#30]
A new copyright update script was added to https://github.com/rapidsai/pre-commit-hooks, and `v0.0.1` was tagged. This check has been deployed in cudf and cuspatial and seems to be working very well. We should deploy this to the rest of RAPIDS too.

**Comment by bdice** [comment]
List of repos needing this: https://github.com/search?q=org%3Arapidsai%20copyright.py&type=code
- cuml
- rapids-cmake
- raft
- wholegraph
- cudf-pandas-integration
- cugraph-ops
- cuvs
- kvikio
- cumlprims_mg

**Comment by mroeschke** [comment]
If we are modifying/adding a file that has vendored code e.g. (`python/cuml/_thirdparty/sklearn/preprocessing/_function_transformer.py`), is it OK to still have the Nvidia copyright note at the top?

**Comment by KyleFromNVIDIA** [comment]
My understanding is that `versioneer.py` has historically been exempt from the copyright notice, so precedent would say no. @bdice is that right?

**Comment by bdice** [comment]
I’ll point you both to a resource about this offline.

@KyleFromNVIDIA There are a few references to copyright.py in developer guides for cuml and raft (possibly more). Just be aware to check for that too.

https://github.com/rapidsai/cuml/blob/334d7960a0690126a58e0be898cdceaa409686f2/wiki/cpp/DEVELOPER_GUIDE.md?plain=1#L202

https://github.com/rapidsai/raft/blob/0b9692b25f78cd1b27631e354e3f8921a976645c/docs/source/developer_guide.md?plain=1#L218

**Comment by bdice** [comment]
It looks like we still have some clean to do here before we can close.

- [ ] Remove the old copyright script from [wholegraph](https://github.com/rapidsai/wholegraph/blob/9d1dcb110430a0f6c5eddf3268e55b16890281a8/scripts/checks/copyright.py#L4) and another internal repo
- [ ] Remove references to the old script from [cuML's developer guide](https://github.com/rapidsai/cuml/blob/6a08a605ca8138b440d336e1abe36e872857c198/wiki/cpp/DEVELOPER_GUIDE.md?plain=1#L202)
- [ ] Remove references to the old script from [RAFT's developer guide](https://github.com/rapidsai/raft/blob/316a06583717c0228a9cc66557c5bed16332365d/docs/source/developer_guide.md?plain=1#L218)
- [ ] Remove references to the old script from [cuVS's developer guide](https://github.com/rapidsai/cuvs/blob/bc9d2d5bbc426ce7cceb975ffc50270f3a4cea78/docs/source/developer_guide.md?plain=1#L218)

References can be seen in this search: https://github.com/search?q=org%3Arapidsai%20copyright.py&type=code
