### ISSUE TITLE
Merge the miniforge-cuda repo into ci-imgs

### ISSUE THREAD

**Issue by vyasr** [rapidsai/build-planning#48]
Currently we build a base image with CUDA and conda installed in [the miniforge-cuda repo](https://github.com/rapidsai/miniforge-cuda), then use that as a base for the conda images in [the ci-imgs repo](https://github.com/rapidsai/ci-imgs/blob/main/ci-conda.Dockerfile). Due to the tight coupling between these images, we trigger a rebuild of the ci-imgs whenever a PR is merged to miniforge-cuda. Given this tight coupling, I think we should consider merging these repos. Combining the repositories will make it easier to teach new build engineers about the pieces we have, and make it easier to maintain since it will reduce the amount of distinct processes required if there are changes that need to be coordinated between the repositories.
```[tasklist]
### Tasks
- [x] run miniforge-cuda builds from https://github.com/rapidsai/ci-imgs: https://github.com/rapidsai/ci-imgs/pull/167
- [x] add a note to README of https://github.com/rapidsai/miniforge-cuda linking to https://github.com/rapidsai/build-planning/issues/48: https://github.com/rapidsai/miniforge-cuda/pull/73
- [x] transition any of the still-relevant open issues from https://github.com/rapidsai/miniforge-cuda/issues over to `ci-imgs`
- [x] archive https://github.com/rapidsai/miniforge-cuda
- [x] update links to that repo in docs (e.g. https://github.com/rapidsai/build-planning/blob/033d3b059ecaf06d920c5f3c113b38b3d77f649c/docs/docs/ci.md?plain=1#L77)
- [x] one more GitHub search for any lingering references to the `miniforge-cuda` repo
```

**Comment by jameslamb** [comment]
I've added a task list here.

**Comment by bdice** [comment]
Here is the search I did for URLs to replace. https://github.com/search?q=org%3Arapidsai+github.com%2Frapidsai%2Fminiforge-cuda&type=code

I don't think there are any besides https://github.com/rapidsai/build-planning/pull/97.

**Comment by bdice** [comment]
I requested archival of `rapidsai/miniforge-cuda`.

**Comment by bdice** [comment]
Archival is complete. Closing this.

**Comment by jameslamb** [comment]
Thanks so much for finishing this up!
