### ISSUE TITLE
Update latest CUDA version for build/test to 12.5

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#73]
With the recent CCCL update (https://github.com/rapidsai/rapids-cmake/pull/607), we should now be able to build RAPIDS with CUDA versions 12.5 and older.

We have CUDA driver R550 in CI now, ~which only supports up to CUDA 12.4, so that's the latest version we could adequately test. CUDA 12.5 needs driver R555, which does not yet have a production branch (PB) or long-term support (LTS) release.~

edit: R550 is a Production Branch driver, and therefore supports CUDA Forward Compatibility with CUDA 12.5 containers. This means we are able to support CUDA 12.5 (the latest version at the time of writing).

I propose to update CI images, shared workflows, devcontainers, etc. to replace CUDA 12.2 with CUDA 12.5. We would retain CI testing for CUDA 12.0 as a lower bound of 12.x. ~This will also align with PyTorch's upcoming CUDA 12.4 support (there have been a series of PRs adding CUDA 12.4 support like https://github.com/pytorch/builder/pull/1720).~ edit: We will upgrade to the latest CUDA, 12.5, instead of 12.4. I will separately address the issues of CUDA compatibility questions between RAPIDS and PyTorch by working on our docs and release selector (see also: https://github.com/rapidsai/build-infra/issues/55).

### Tasks
- [x] Add 12.5.0 miniforge-cuda images https://github.com/rapidsai/miniforge-cuda/pull/67
- [x] Add 12.5.0 CI images https://github.com/rapidsai/ci-imgs/pull/153
- [x] Update miniforge-cuda to 12.5.1 https://github.com/rapidsai/miniforge-cuda/pull/71
  - Depends on https://gitlab.com/nvidia/container-images/cuda being updated to 12.5.1
    - Done in https://gitlab.com/nvidia/container-images/cuda/-/commit/85f465ea3343a2d7f7753a0a838701999ed58a01
- [x] Update CI images to 12.5.1 (after miniforge-cuda update) https://github.com/rapidsai/ci-imgs/pull/159

We can start this work now (not blocked by 12.5.1 updates above):
- [x] Open PR to shared-workflows https://github.com/rapidsai/shared-workflows/pull/229
  - Similar to [prior work on CUDA 12.2](https://github.com/rapidsai/shared-workflows/pull/166), except we're just replacing 12.2.2 with 12.5.x
- [x] Open PRs for every RAPIDS repository to update 12.2.2 to 12.5.x (xref'd below)
  - See [past CUDA 12.2 migration PRs](https://github.com/search?q=org%3Arapidsai+%22Support+CUDA+12.2%22&type=pullrequests) for reference.
  - Most of the items below can be automated:
    - Add `cuda-version` matrix entry for 12.5
    - Update `.github/workflows/` to use shared-workflows branch
    - Update any `matrix_filter` entries using 12.2 to 12.5
    - Update README/CONTRIBUTING docs to use 12.5, especially for installation
    - Update devcontainers to 12.5
  - [x] rmm
  - [x] cudf
  - [x] ...
- [x] Publish new images from `rapidsai/docker` (https://github.com/rapidsai/docker/pull/689)

Once all repos are migrated, merge the `shared-workflows` PR and then revert to the current default `shared-workflows` branch.

Docs changes (wait until all repos are migrated):
- [x] Update release selector for nightlies ([past example](https://github.com/rapidsai/docs/pull/483)) https://github.com/rapidsai/docs/pull/522
- [ ] Update release selector for stable builds at release time ([past example](https://github.com/rapidsai/docs/pull/506)): https://github.com/rapidsai/docs/pull/529
- [ ] Update rapids.ai at release time ([past example](https://github.com/rapidsai/rapids.ai/pull/372)): https://github.com/rapidsai/rapids.ai/pull/389

**Comment by mmccarty** [comment]
@ajschmidt8 - Please take a look at the possibility of updating this in July.

**Comment by bdice** [comment]
I’ve spent a bit of time investigating and discussing this topic with others (including @jrhemstad). I’m coming to the conclusion that we may not need any driver updates, because the Production Branch driver we currently use (R550) is supported for CUDA Forward Compatibility according to this table: https://docs.nvidia.com/deploy/cuda-compatibility/#id3

My local tests on a machine with R535, the LTS driver, also indicate compatibility should be fine.

I propose a change to this plan: we should try to use CUDA 12.5 to build and test for a couple repos (rmm and cudf) and if it works we can update to 12.5 instead of 12.4. I will file PRs to the miniforge-cuda, ci-imgs, and shared-workflows repositories to enable this test.

**Comment by jakirkham** [comment]
It is worth noting that CUDA 12.5.1 packages (in various formats) are now out

Also `pynvjitlink` has been rebuilt with CUDA 12.5.1: https://github.com/rapidsai/pynvjitlink/pull/95

**Comment by jakirkham** [comment]
Looking at this one...

> * [ ] Update miniforge-cuda to 12.5.1
>    * Depends on https://gitlab.com/nvidia/container-images/cuda being updated to 12.5.1

It appears the builds are already pulling in the latest distro packages for CUDA 12.5.1

For example [this job from yesterday]( https://github.com/rapidsai/miniforge-cuda/actions/runs/9848841134/job/27191553920#step:7:399 ), shows the following

```
#13 4.389  cuda-compat-12-5                x86_64 1:555.42.06-1           cuda       38 M
#13 4.389  cuda-cudart-12-5                x86_64 12.5.82-1               cuda      226 k
#13 4.389  cuda-toolkit-12-5-config-common noarch 12.5.82-1               cuda      7.7 k
#13 4.389  cuda-toolkit-12-config-common   noarch 12.5.82-1               cuda      7.9 k
#13 4.389  cuda-toolkit-config-common      noarch 12.5.82-1               cuda      7.9 k
```

Note that these match [the new versions in CUDA 12.5U1]( https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html )

So looks like this is done already

Though it would be nice to update [this `miniforge-cuda` line to `12.5.1`]( https://github.com/rapidsai/miniforge-cuda/blob/0e20886991c4fcb178d73bd0f1cf3224d1b0e0a8/matrix.yaml#L6 ), it doesn't seem to be a blocker

**Comment by jakirkham** [comment]
cc @KyleFromNVIDIA (as we discussed this offline)

**Comment by jakirkham** [comment]
NVIDIA CUDA 12.5.1 images were released recently. So Kyle and I have updated the RAPIDS images to use them

* https://github.com/rapidsai/miniforge-cuda/pull/71
* https://github.com/rapidsai/ci-imgs/pull/159

Added a few notes in the OP. More details in the linked PRs

**Comment by jameslamb** [comment]
After all the libraries have been updated, I think we'll also want to add `rapidsai/base` and `rapidsai/notebooks` images, similar to https://github.com/rapidsai/docker/pull/634. Is that tracked anywhere?

I don't know enough about the resource constraints on Docker Hub to say with confidence whether that change should look like just "add CUDA 12.5 images" or should be "stop publishing CUDA 12.2 images and start publishing CUDA 12.5 images". Maybe @raydouglass or @ajschmidt8 could comment on that.

You can see in https://hub.docker.com/r/rapidsai/notebooks/tags that the tagging scheme has `-cuda{major}.{minor}` in it.

**Comment by jakirkham** [comment]
We noticed the `.devcontainer`s contents were updated for CUDA 12.5, but the `.devcontainer`s path names were not. Submitted a few PRs to cleanup already merged ones. Also pushed changes to open PRs to fix this. Made a note for us to update our PR generation scripts to address this going forward

**Comment by jakirkham** [comment]
Just an update here, we have gotten the bulk of RAPIDS projects onto CUDA 12.5

One exception is cuSpatial where we are noticing issues with the notebook tests. This occurs without CUDA 12.5 as well. James has been investigating in PR ( https://github.com/rapidsai/cuspatial/pull/1407 ) and will be following up with the cuSpatial team on next steps

**Comment by jameslamb** [comment]
I'm proposing switching to CUDA 12.5 images + Python 3.11 in the docs at https://docs.rapids.ai/deployment

https://github.com/rapidsai/deployment/pull/398

**Comment by jakirkham** [comment]
For completeness, this is largely complete. All that remains is...

* Adding this to the rapids.ai main page
* Adding this to the stable install selector (currently it is only under nightlies)

Both of which are in the checklist in the OP

These typically happen after the release is complete

**Comment by jakirkham** [comment]
Ok the remaining webpage PRs are up. Thanks Ray! 🙏

Have noted those above and xref'd them here

**Comment by jakirkham** [comment]
Closing as completed 🥳

Thanks everyone for all of your hard work shipping CUDA 12.5 this release! 👏

**Comment by bdice** [comment]
For future reference: `gputreeshap` was missed during this upgrade. https://github.com/rapidsai/gputreeshap/pull/50#issuecomment-2296966063

**Comment by jakirkham** [comment]
It's a little hard to know what to do with that repo given cuML seems to vendor it. We've also struggled with updating it in the past. Maybe we should have a separate discussion on how it should be managed
