### ISSUE TITLE
skip cmake 3.30.0 across RAPIDS

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/build-planning#80]
## Description

With the release of CMake 3.30.0, we started observing configure errors like the following across a couple RAPIDS projects:

```text
-- Configuring done (13.1s)
CMake Error at CMakeLists.txt:669 (target_link_libraries):
  The link interface of target "raft_distributed" contains:

    ucx::ucp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

([build link](https://github.com/rapidsai/raft/actions/runs/9772300825/job/26976475463))

* report: https://gitlab.kitware.com/cmake/cmake/-/issues/26108
* MR that would fix this in a CMAKE 3.30.1 release: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9643

Until a v3.30.1 of CMake is released with a fix, RAPIDS libraries should skip v3.30.0, with pins like this:

```text
cmake >=3.26.4,!=3.30.0
```

## Benefits of this work

* unblocks development across RAPIDS

## Acceptance Criteria

* CI is no longer blocked, in any RAPIDS repo, by this particular CMake issue

## Approach

Use `rapids-reviser`, add a `!=3.30.0` pin to all the CMake pins.

## Notes

Using a `!=` is preferable to a ceiling here, because:

* no need to do another round of updates once a v3.30.1 with a fix is released
* reduces the risk of getting v3.30.0 during development in the future

Identified the repos that need this via this GitHub search: https://github.com/search?q=org%3Arapidsai%20%22cmake%3E%3D%22%20AND%20NOT%20is%3Aarchived&type=code

```[tasklist]
### Tasks
- [x] cucim (https://github.com/rapidsai/cucim/pull/745)
- [x] cudf (https://github.com/rapidsai/cudf/pull/16202)
- [x] cugraph (https://github.com/rapidsai/cugraph/pull/4522)
- [x] cugraph-gnn (https://github.com/rapidsai/cugraph-gnn/pull/8)
- [ ] cugraph-pg (https://github.com/rapidsai/cugraph-pg/pull/23)
- [x] cuml (https://github.com/rapidsai/cuml/pull/5956)
- [x] cuspatial (https://github.com/rapidsai/cuspatial/pull/1401)
- [x] cuvs (https://github.com/rapidsai/cuvs/pull/214)
- [x] kvikio (https://github.com/rapidsai/kvikio/pull/400)
- [ ] private repos (see links below)
- [x] pynvjitlink (https://github.com/rapidsai/pynvjitlink/pull/94)
- [x] raft (https://github.com/rapidsai/raft/pull/2375)
- [x] rmm (https://github.com/rapidsai/rmm/pull/1603)
- [x] ucxx (https://github.com/rapidsai/ucxx/pull/244)
- [x] wholegraph (https://github.com/rapidsai/wholegraph/pull/189)
```

**Comment by jakirkham** [comment]
With the exception of cuGraph-PG, which is covered in this comment ( https://github.com/rapidsai/cugraph-pg/pull/23#issuecomment-2219034553 ), these are complete. Let's close this out. Thanks James! 🙏
