### ISSUE TITLE
Drop support for Python 3.9

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#88]
This issue tracks dropping Python 3.9, following from the discussion on https://github.com/rapidsai/build-planning/issues/40:

>### When should we drop Python 3.9?
> Typically RAPIDS has kept the matrix of supported Python minor versions to 2 or 3 versions at a time. When adding Python 3.12, we should probably drop Python 3.9 as well.
>
> [SPEC 0](https://scientific-python.org/specs/spec-0000/) recommended dropping support for Python 3.9 in 2023Q4. Meanwhile, [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommended dropping support for Python 3.9 as of Apr 05, 2024. Both of these deadlines have passed and several large Python libraries are now moving towards dropping Python 3.9, so it is probably reasonable to drop Python 3.9 around the same time that we add Python 3.12.

We are beyond the SPEC 0 date for dropping Python 3.9 now, and expect that RAPIDS dependencies will gradually drop support. We are exploring dropping Python 3.9 in RAPIDS 24.10.

Tasks:
- [x] Announce deprecation: https://github.com/rapidsai/docs/pull/528
- [x] Drop Python 3.9 from shared-workflows: https://github.com/rapidsai/shared-workflows/pull/235
- [x] For each repo, update Python requirements
  - [x] Update [matrix filters referencing Python 3.9](https://github.com/rapidsai/cudf/blob/9336c172b1f61408e2392cbbd953e7f7e6e9ae3d/.github/workflows/pr.yaml#L199)
  - [x] Edit `dependencies.yaml` to remove [`py: 3.9` sections like this](https://github.com/rapidsai/cudf/blob/9336c172b1f61408e2392cbbd953e7f7e6e9ae3d/dependencies.yaml#L539-L542)
  - [x] Edit `dependencies.yaml` to raise the fallback matrix's [Python lower bound](https://github.com/rapidsai/cudf/blob/9336c172b1f61408e2392cbbd953e7f7e6e9ae3d/dependencies.yaml#L551-L553)
  - [x] Update CMake references [like `find_package(Python 3.9 ...)`](https://github.com/rapidsai/cudf/blob/9336c172b1f61408e2392cbbd953e7f7e6e9ae3d/python/cudf/CMakeLists.txt#L34)
  - [x] Update `pyproject.toml`: [`requires-python`](https://github.com/rapidsai/cudf/blob/9336c172b1f61408e2392cbbd953e7f7e6e9ae3d/python/cudf/pyproject.toml#L19) and [specifiers](https://github.com/rapidsai/cudf/blob/9336c172b1f61408e2392cbbd953e7f7e6e9ae3d/python/cudf/pyproject.toml#L43)
  - [x] Check for special cases, like [ucxx's Python build matrix in conda_build_config.yaml](https://github.com/rapidsai/ucxx/blob/c0acb1ec7c3081c446b8b5b56042d22c18b7d22b/conda/recipes/ucxx/conda_build_config.yaml#L22-L25)
  - [x] Update README, CONTRIBUTING, and docs as needed
  - [x] grep for `3.9` to make sure nothing was missed!

Things to be careful about:

* Python version embedded in Jupyter notebook metadata ([like this](https://github.com/rapidsai/cuml/blob/220bf8ff435ec2be32d9d1d3b78b5febbcb5f116/notebooks/arima_demo.ipynb?short_path=1b926b2#L517))
* avoid changing benchmarking results and the code to reproduce them
* `pynvjitlink` is used by more than just RAPIDS (like https://github.com/NVIDIA/nvmath-python), and uses its own CI matrix to support a broader range of versions than RAPIDS ([link](https://github.com/rapidsai/pynvjitlink/blob/a2f23b7c3c237f2cdde3093c845e0453572503eb/.github/actions/compute-matrix/action.yaml#L19))... we may sometimes drop a Python version across RAPIDS but still support it in `pynvjitlink`
* generic tools like `rapids-reviser`, `rapids-build-backend`, `rapids-metadata`, etc. shouldn't have their floors bumped unless there's a compelling reason to do so... that'd make it harder to fix bugs in those tools that affect older releases

```[tasklist]
### before making changes in individual repos
- [x] Announce deprecation: https://github.com/rapidsai/docs/pull/528
- [x] Drop Python 3.9 from shared-workflows: https://github.com/rapidsai/shared-workflows/pull/235
```

```[tasklist]
### Updates for libraries
- [x] cucim (https://github.com/rapidsai/cucim/pull/766)
- [x] cudf (https://github.com/rapidsai/cudf/pull/16637)
- [x] cugraph (https://github.com/rapidsai/cugraph/pull/4625)
- [x] cugraph-gnn (https://github.com/rapidsai/cugraph-gnn/pull/32)
- [x] cugraph-pg (https://github.com/rapidsai/cugraph-pg/pull/25 ... this repo is not being actively developed right now, not waiting for that to be mered to consider this done)
- [x] cuml (https://github.com/rapidsai/cuml/pull/6040)
- [x] cuspatial (https://github.com/rapidsai/cuspatial/pull/1443)
- [x] cuvs (https://github.com/rapidsai/cuvs/pull/301)
- [x] cuxfilter (https://github.com/rapidsai/cuxfilter/pull/623)
- [x] dask-cuda (https://github.com/rapidsai/dask-cuda/pull/1377)
- [x] kvikio (https://github.com/rapidsai/kvikio/pull/443)
- [x] pynvjitlink (https://github.com/rapidsai/pynvjitlink/pull/102)
- [x] rapids-cmake (https://github.com/rapidsai/rapids-cmake/pull/684)
- [x] raft (https://github.com/rapidsai/raft/pull/2417)
- [x] rmm (https://github.com/rapidsai/rmm/pull/1659)
- [x] ucx-py (https://github.com/rapidsai/ucx-py/pull/1065)
- [x] ucxx (https://github.com/rapidsai/ucxx/pull/272)
- [x] wholegraph (https://github.com/rapidsai/wholegraph/pull/209)
- [x] private repos
```

```[tasklist]
### after all libraries are updated
- [x] `pypi-wheel-scripts` (https://github.com/rapidsai/pypi-wheel-scripts/pull/16)
- [x] `ci-imgs` (https://github.com/rapidsai/ci-imgs/pull/173)
- [x] dask-build-environment (https://github.com/rapidsai/dask-build-environment/pull/97)
- [x] update install docs? (https://github.com/rapidsai/docs/blob/01dbbcb67c199893b839651f5dca01356c825068/install/install.md?plain=1#L101) (https://github.com/rapidsai/docs/pull/534)
- [x] Update release selector: need to disable Python 3.9 on nightlies https://github.com/rapidsai/docs/blob/01dbbcb67c199893b839651f5dca01356c825068/_includes/selector.html (https://github.com/rapidsai/docs/pull/534)
```

**Comment by jakirkham** [comment]
Some quick data points:

* NumPy 2.1.0 drops Python 3.9 (note 2.0.0 has 3.9 support)
  * https://github.com/numpy/numpy/issues/26242
* Pandas next release drops Python 3.9 (cites SPEC 0)
  * https://github.com/pandas-dev/pandas/pull/58238
* CuPy 14 plans to drop Python 3.9 (cites SPEC 0)
  * https://github.com/cupy/cupy/issues/8269
* Numba still [supports Python 3.9]( https://github.com/numba/numba/blob/99f5cc6750ea92ffc619377565bbecadff4217bb/setup.py#L22 )
* scikit-learn still [supports Python 3.9]( https://github.com/scikit-learn/scikit-learn/blob/234260dfb7fc615c2adfa90f8c6405200971efc2/pyproject.toml#L15 )
* scikit-image still [supports Python 3.9]( https://github.com/scikit-image/scikit-image/blob/ee41933e3ea15769cea32a514cdaeecbe84b70b9/pyproject.toml#L4 )
* NetworkX 3.3 dropped Python 3.9 (came out Oct 2023)
  * https://github.com/networkx/networkx/pull/7028
* Bokeh 3.5 dropped Python 3.9
  * https://github.com/bokeh/bokeh/pull/13634
* Dask is discussing dropping Python 3.9
  * https://github.com/dask/community/issues/373
 * XGBoost next release drops Python 3.9
   * https://github.com/dmlc/xgboost/pull/10434

**Comment by jameslamb** [comment]
I'm +1 on doing this in this timeframe.

DLFW builds are using Python 3.10 ([DLFW support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html)), as  as that's the stable python3 that ships with Ubuntu 22.04 ([Python version across Linux distros](https://repology.org/project/python/versions)), so this change shouldn't be disruptive for those builds.

And `nemo-curator` is on `python >= 3.10` ([code link](https://github.com/NVIDIA/NeMo-Curator/blob/62fdee8d89d2d9d87ab9e045f44f8c86bd45f903/setup.py#L40)), so they shouldn't be affected either.

**Comment by rjzamora** [comment]
>We are exploring dropping Python 3.9 in RAPIDS 24.10.

Just curious to know what the ETA is for dropping Python 3.9?

I believe we will need to remain pinned to dask 2024.7.1 until then. In the meantime, we cannot catch breaking changes in dask/distributed.

**Comment by jameslamb** [comment]
The plan is to do this "within 24.10", but we can't be more precise than that.

> I believe we will need to remain pinned to dask 2024.7.1 until then. In the meantime, we cannot catch breaking changes in dask/distributed.

For Python 3.9, yes, but I think `rapids-dask-dependency` could take on a dependency on newer `dask` / `distributed` for Python 3.10+

Like this:

```toml
# TODO: drop the python_version specifiers and just use latest versions built from GitHub once
#              RAPIDS drops Python 3.9 support
dependencies = [
    "dask @ git+https://github.com/dask/dask.git@main ; python_version >= '3.9'",
    "distributed @ git+https://github.com/dask/distributed.git@main ; python_version >= '3.10'",
    "dask-expr @ git+https://github.com/dask/dask-expr.git@main ; python_version >= '3.10'",
    "dask==2024.7.1 ; python_version < '3.10'",
    "distributed==2024.7.1 ; python_version < '3.10'",
    "dask-expr ; python_version < '3.10'",
]
```

That'd allow projects to start testing against the latest development version of Dask throughout the 24.10 release cycle.

**Comment by rjzamora** [comment]
>That'd allow projects to start testing against the latest development version of Dask throughout the 24.10 release cycle.

Okay, thanks for the response @jameslamb! This may be our best option -- I'll look into it.

**Comment by jakirkham** [comment]
For `rapids-dask-dependency`, likely Conda will work ok as-is since the solver will pick packages that are Python 3.9 (or 3.10+) compatible. Though please let us know if not

**Comment by bdice** [comment]
Dropping 3.9 builds should now be safe, and would also unblock the work of updating our dask pinning.

This PR does that: https://github.com/rapidsai/shared-workflows/pull/235

This change in `shared-workflows` is also safe to merge _before_ we do the cleanup in each repo to remove dependencies, configs, etc. referencing Python 3.9. We're just building/testing fewer packages.

**Comment by jakirkham** [comment]
Closing the loop on Dask, we dropped Python 3.9 from CI, so no special casing was needed (or used) there

Just a normal unpinning of Dask as part of RAPIDS post-release cleanup

**Comment by jakirkham** [comment]
Thanks James! 🙏

Have shepherded a good chunk of these through

Of the remainder:

* RAFT - Had a (flaky?) test failure. Trying rerunning to see if it clears
* cuGraph-GNN & Wholegraph - Have active discussions (though seems like they are close to resolution)
* Draft PRs - A few are marked as draft. Maybe we can take them out of draft?
* Others - Did not get to some or saw others were already looking

Please let me know if there are others you need help following up on

**Comment by jameslamb** [comment]
Thanks John!

> *A few are marked as draft. Maybe we can take them out of draft?*

Yep, my approach has been to open these PRs in draft first, to not bother people with notifications for review until I see CI (or at least, most CI) passing.

Happy to see all of those that were still in draft as of yesterday are looking ok, so I've opened them all up for review.

**Comment by sisodia1701** [comment]
Discussed in today's build infra sync, this is almost done. Once complete, the team will start working on [Add support for Python 3.12](https://github.com/rapidsai/build-planning/issues/40)	https://github.com/rapidsai/build-planning/issues/40

**Comment by jameslamb** [comment]
Did another set of GitHub searches, and I think this work is now complete! Thanks for the help everyone 😁
